-- Ejecutar UNA sola vez en Supabase > SQL Editor.
-- Hace editables desde Acceso interno los contactos de Donaciones y Áreas.

create table if not exists public.configuracion_contactos (
  clave text primary key,
  nombre text not null,
  whatsapp text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.areas_contacto (
  id bigint generated by default as identity primary key,
  area_id text not null unique,
  encargado text not null default '',
  whatsapp text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.configuracion_contactos(clave,nombre,whatsapp)
values ('donaciones','Nataly Carhuamaca','51938137626')
on conflict (clave) do update set nombre=excluded.nombre, whatsapp=excluded.whatsapp, updated_at=now();

insert into public.areas_contacto(area_id,encargado,whatsapp) values
('integracion','Melissa','51925987060'),
('tecnica','',''),
('difusion','Eduardo','51954088882'),
('cafeteria','Roxana','51964002963'),
('redes','Isa','51930512158'),
('cultura','Brandol','51916012400'),
('escolastica-prob','Angelita','51927139028'),
('escolastica-miembros','Clayre','51943944640')
on conflict (area_id) do nothing;

alter table public.configuracion_contactos enable row level security;
alter table public.areas_contacto enable row level security;

drop policy if exists "contactos lectura publica" on public.configuracion_contactos;
create policy "contactos lectura publica" on public.configuracion_contactos for select using (true);
drop policy if exists "areas lectura publica" on public.areas_contacto;
create policy "areas lectura publica" on public.areas_contacto for select using (true);

drop policy if exists "contactos admin update" on public.configuracion_contactos;
create policy "contactos admin update" on public.configuracion_contactos for all to authenticated
using (public.es_admin_actual()) with check (public.es_admin_actual());

drop policy if exists "areas admin update" on public.areas_contacto;
create policy "areas admin update" on public.areas_contacto for all to authenticated
using (public.es_admin_actual()) with check (public.es_admin_actual());

-- El encargado de donaciones también puede cambiar SU contacto de donaciones.
drop policy if exists "contactos donaciones responsable" on public.configuracion_contactos;
create policy "contactos donaciones responsable" on public.configuracion_contactos for update to authenticated
using (clave='donaciones' and exists (select 1 from public.mis_roles_actuales() r where r.rol='encargado_donaciones'))
with check (clave='donaciones' and exists (select 1 from public.mis_roles_actuales() r where r.rol='encargado_donaciones'));

grant select on public.configuracion_contactos, public.areas_contacto to anon, authenticated;
grant insert, update, delete on public.configuracion_contactos, public.areas_contacto to authenticated;
notify pgrst, 'reload schema';
